name: Continuous Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main
      - epic/*
      - feature/*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: write-all
env:
  HUB_USER: flaviuspetrisor

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: flaviuspetrisor/qed:base
      credentials:
        username: ${{ env.HUB_USER }}
        password: ${{ secrets.HUB_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prerequisites
        run: npm install --save-dev mocha assert

      - name: Test
        run: npm run test

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.HUB_USER }}
          password: ${{ secrets.HUB_PASS }}

      - name: Image Build and Push
        run: |
          docker build -t ${{ env.HUB_USER }}/qed .
          docker push ${{ env.HUB_USER }}/qed
        shell: bash

      - name: Workspace Clean
        if: always()
        run: find . -mindepth 1 -maxdepth 1 -exec rm -rf {} + || true